### ISSUE TITLE
Another actively developed fork of zfs-fuse?

### ISSUE THREAD

**Issue by Conan-Kudo** [gordan-bobic/zfs-fuse#15]
Hey,

It seems that there's another (semi-)actively developed [fork of zfs-fuse](https://github.com/pscedu/zfs-fuse). Perhaps it might be a good idea to pool efforts to improve it, since it seems like you are making different fixes from them. Or perhaps pull in their stuff into this project?

In any case, you might want to look into it.

**Comment by gordan-bobic** [comment]
If they want to pull in all of my fixes and features (including support for pool versions up to v28, and take over maintenance I would welcome this. Since Linux kernel ZFS port now works reasonably on 32-bit ARM machines I no longer have a use for zfs-fuse, so my motivation for continuing maintaining it is rather low. My branch seems to currently be the only one with pool v28 support.
