### ISSUE TITLE
Some files missing from the spec file..

### ISSUE THREAD

**Issue by ElCoyote27** [gordan-bobic/zfs-fuse#9]
Hi Gordan,
I was attempting to rebuild the rpms while using your spec file and zfs-fuse repo and I ran into this:

rpmbuils -bs ...zfs-fuse.spec
[...]
    Bad file: /usr/src/redhat/SOURCES/zfs-fuse.modules-load: No such file or directory
    Bad file: /usr/src/redhat/SOURCES/zfs-fuse.zfsrc: No such file or directory
    Bad file: /usr/src/redhat/SOURCES/zfs-fuse.init: No such file or directory
These do not appear to be in your tree (they were in mine).
Would you want to add them to the tree or are they not needed anymore?
I hope you didn't inherit this issue by merging my tree.. (it could be)

**Comment by gordan-bobic** [comment]
I don't think you included them in the pull request. However, take a look at the /contrib folder, I think you will find everything needed in there. I am rapidly moving everything onto EL7 so it is possible I may have overlooked some EL5/EL6 things. If you have a fix, by all means push it in my direction.

**Comment by ElCoyote27** [comment]
Hi Gordan,
Also, I noticed that
-fstrict-volatile-bitfields doesn't work on EL5/EL6.
I'm also moving quickly onto EL7 but I still attempt to support some older clients.
I'll have a merge request shortly (I hope).

**Comment by gordan-bobic** [comment]
Ah, fair enough, as I said, I hadn't tested with older versions of gcc. I propose a separate patch (in contrib) that reverses commit https://github.com/gordan-bobic/zfs-fuse/commit/66657036a19a922693337c5f7023dbde7f4d75bb that can be applied conditionally by the spec file for rhel <= 6.

**Comment by gordan-bobic** [comment]
Just out of interest what are your specific uses of zfs-fuse (i.e. why not ZoL)? Just for 32-bit servers or are there other reasons?

**Comment by ElCoyote27** [comment]
Hi Gordan,
Having several old EL5/EL6 systems with SAN, it's easier to use zfs-fuse for one-shot migrations.
Thank you for your assistance,
Regards,
Vincent

**Comment by gordan-bobic** [comment]
I have done a bit more cleaning up of the git tree. All the /etc/ files used on rpm based distros are now in the root directory of the git tree and referenced directly in the spec file without requiring to be manually copied to the SOURCE directory before building.

Still cannot quite get it to build directly from the tar ball though, it complains about the lack of libumem-1.0.1.tar.bz2.

**Comment by ElCoyote27** [comment]
Interesting.. with the latest tree I had sent you it compiles without any issue..
Do you have more details?

**Comment by gordan-bobic** [comment]
Check out the master branch from git, rename folder from zfs-fuse to zfs-fuse-0.7.2.1, tar -Jcvf it, then to rpmbuild -tb zfs-fuse-0.7.2.1.tar.xz
It fails saying it couldn't find libumem-1.0.1.tar.bz2
This is on EL7.

**Comment by ElCoyote27** [comment]
I just did that and I'm not seeing any issues on el6.
the previous tree didn't have any issue (tested on rhel5/6/7). Currently re-testing on RHEL7.

**Comment by ElCoyote27** [comment]
Works fine for me on el7.1:
[raistlin@rh7x64 GIT]$ rpmbuild -tb zfs-fuse-0.7.2.1.tar.xz 
[....]
Checking for unpackaged file(s): /usr/lib/rpm/check-files /export/home/raistlin/rpmbuild/BUILDROOT/zfs-fuse-0.7.2.1-1.el7.x86_64
Wrote: /export/home/raistlin/rpmbuild/RPMS/x86_64/zfs-fuse-0.7.2.1-1.el7.x86_64.rpm
Wrote: /export/home/raistlin/rpmbuild/RPMS/x86_64/zfs-fuse-debuginfo-0.7.2.1-1.el7.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.tzdmwi
- umask 022
- cd /export/home/raistlin/rpmbuild/BUILD
- cd zfs-fuse-0.7.2.1
- /usr/bin/rm -rf /export/home/raistlin/rpmbuild/BUILDROOT/zfs-fuse-0.7.2.1-1.el7.x86_64
- exit 0

**Comment by ChenHuge** [comment]
Very happy to see this project, thank for the maintainers.
I notice that the zfs-fuse without  the encryption property, without lz4 compression, without the fletcher4 dedup. 
zfs-fuse will be perfect if with those feature.

**Comment by gordan-bobic** [comment]
@ElCoyote27 Glad to hear it works for you. I'll take a closer look and see if I can reproduce a working environment and tag the recent changes as a 0.7.2.2 release.

@ChenHuge Good to hear from more people who use zfs-fuse (I presume you use it if you're following the project). On the subject of points you raised:
1) Encryption isn't supported most open source ZFS ports. The long term aim with zfs-fuse is to try to reach parity with ZoL, which also doesn't support encryption. Until encryption is implemented (don't hold your breath, it likely won't be any time soon) the recommended approach is to use dm-crypt (with or without LUKS) on top of the raw device and put the ZFS pool on top of that.
2) AFAIK sha256 is the default choice for deduplication on other implementations as well. What implementation allows you to use fletcher with deduplication? IMO any development effort in this area would be better directed in using sha256 implementation from OpenSSL so that built in crypto offload engines in many ARM SoCs can be used to offload sha256 calculations. If that can be achieved sha256 checksumming would effectively become free in terms of CPU usage (provided the SoC in question has hardware crypto offload unit capable of sha256, which many do).
3) lz4 compression would indeed be a nice addition to have, but that would require adding support for pool version 5000 with feature flag support in addition to lz4 support, which is going to require some non-trivial porting and exhaustive testing. On the other hand, lzjb compression is actually pretty good. It produces similar compression ratios, and while it does require more CPU time than lz4 it isn't too bad - it is still much cheaper than gzip1.

But if you want to have a go at porting the support for pool version 5000 and lz4, I do accept patches. :)

**Comment by gordan-bobic** [comment]
@ElCoyote27 Confirmed the tar ball build now works correctly. I will tag the 0.7.2.2 release from the current master.

**Comment by ChenHuge** [comment]
I tried to add the encryption to zfs-fuse(I found an encryption version native ZFS), but I am poor in linux programing.......
I use the zfs-fuse to backup files to a file based zfs file system.
As this:  
dd if=/dev/zero of=/zfs_img/backup.img bs=1G count=0 seek=256
zpool create /zfs_img/backup.img my_backup
zfs set compression=lzo my_backup
zfs set dedup=on my_backup
..................

At this way, how to I encrypt it?
Thank you.

**Comment by gordan-bobic** [comment]
Google for "zfs luks", that should point you in the correct direction.
